name: "Test application"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(make composer-cache-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Initialise environment
        run: make prep-ci

      - name: Run static analysis
        run: make static-analysis

      - name: Run behaviour tests
        run: make behaviour

      - name: Run unit and functional tests
        run: make unit-tests

      - name: Cleanup
        if: always()
        run: make clean
